doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Task\App\Cart\Domain:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine_mapping/cart'
                prefix: 'Task\App\Cart\Domain'
            Task\App\Catalogue\Domain:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine_mapping/catalogue'
                prefix: 'Task\App\Catalogue\Domain'
            Task\App\Common\Event:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine_mapping/common/event'
                prefix: 'Task\App\Common\Event'
            Task\App\Common\Price:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine_mapping/common/price'
                prefix: 'Task\App\Common\Price'
